version: "3"
services:
  fastapi-app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgres-db
    
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: music_appln
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

